name : CD Pipeline

on:
   workflow_run:
       workflows: ["CI Pipeline"]
       types:
           - completed
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull parthsinha18/threejs-app:latest
    - name: Delete Old Docker conatiner
      run: sudo docker rm -f threejs-app-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name threejs-app-container parthsinha18/threejs-app
